# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlexaSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('app_label', models.CharField(help_text='Enter the django app label this skill, needed to route incoming requests to the correct django app', max_length=100, verbose_name='Django App Label')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skill_id', models.CharField(max_length=100, verbose_name='API Key')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
